name: Deploy FastAPI to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            source ~/miniconda3/etc/profile.d/conda.sh
            conda activate bio4
            cd ~/workspace/team_proj
            git pull origin main
            pip install -r requirements.txt
            pkill -f "python main.py" || true
            sleep 1
            nohup python main.py > app.log 2>&1 < /dev/null &
            disown